<?php

add_action('acf/include_fields', function() {
   if (!function_exists('acf_add_local_field_group')) {
      return;
   }

   acf_add_local_field_group([
      'key'    => 'group_687ebbae9ac4d',
      'title'  => 'Para Desafios',
      'fields' => [
         [
            'key'               => 'field_6886653936cf3',
            'label'             => 'Sequencial',
            'name'              => 'sequential',
            'aria-label'        => '',
            'type'              => 'true_false',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'message'           => '',
            'default_value'     => 0,
            'allow_in_bindings' => 0,
            'ui'                => 0,
            'ui_on_text'        => '',
            'ui_off_text'       => '',
         ],
         [
            'key'               => 'field_68866e5db9257',
            'label'             => 'Por clube',
            'name'              => 'per_club',
            'aria-label'        => '',
            'type'              => 'true_false',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'message'           => '',
            'default_value'     => 0,
            'allow_in_bindings' => 0,
            'ui'                => 0,
            'ui_on_text'        => '',
            'ui_off_text'       => '',
         ],
         [
            'key'               => 'field_68c0a8d87a4ae',
            'label'             => 'Número de textos',
            'name'              => 'text_count',
            'aria-label'        => '',
            'type'              => 'number',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => 0,
            'min'               => 0,
            'max'               => 4,
            'allow_in_bindings' => 0,
            'placeholder'       => '',
            'step'              => '',
            'prepend'           => '',
            'append'            => '',
         ],
         [
            'key'               => 'field_68c0a9167a4af',
            'label'             => 'Número de textos publicados',
            'name'              => 'publish_count',
            'aria-label'        => '',
            'type'              => 'number',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => 0,
            'min'               => 0,
            'max'               => 4,
            'allow_in_bindings' => 0,
            'placeholder'       => '',
            'step'              => '',
            'prepend'           => '',
            'append'            => '',
         ],
         [
            'key'               => 'field_68bf379598839',
            'label'             => 'Slots',
            'name'              => 'slots',
            'aria-label'        => '',
            'type'              => 'group',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'layout'     => 'block',
            'sub_fields' => [
               [
                  'key'               => 'field_688663c87a9e8',
                  'label'             => 'Slot 1',
                  'name'              => 's0',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'text',
                  ],
                  'post_status'          => '',
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 1,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 1,
                  'bidirectional_target' => [
                     0 => 'field_687edcd59c9da',
                  ],
                  'ui' => 1,
               ],
               [
                  'key'               => 'field_68bf38828ff38',
                  'label'             => 'Slot 2',
                  'name'              => 's1',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'text',
                  ],
                  'post_status'          => '',
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 1,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 1,
                  'bidirectional_target' => [
                     0 => 'field_687edcd59c9da',
                  ],
                  'ui' => 1,
               ],
               [
                  'key'               => 'field_68bf388c8ff39',
                  'label'             => 'Slot 3',
                  'name'              => 's2',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'text',
                  ],
                  'post_status'          => '',
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 1,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 1,
                  'bidirectional_target' => [
                     0 => 'field_687edcd59c9da',
                  ],
                  'ui' => 1,
               ],
               [
                  'key'               => 'field_68bf38968ff3a',
                  'label'             => 'Slot 4',
                  'name'              => 's3',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'text',
                  ],
                  'post_status'          => '',
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 1,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 1,
                  'bidirectional_target' => [
                     0 => 'field_687edcd59c9da',
                  ],
                  'ui' => 1,
               ],
            ],
         ],
      ],
      'location' => [
         [
            [
               'param'    => 'post_type',
               'operator' => '==',
               'value'    => 'challenge',
            ],
         ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
      'display_title'         => '',
   ]);

   acf_add_local_field_group([
      'key'    => 'group_68811a2d2d888',
      'title'  => 'Para Global',
      'fields' => [
         [
            'key'               => 'field_688c33bb6cfdf',
            'label'             => 'Páginas',
            'name'              => 'pages',
            'aria-label'        => '',
            'type'              => 'group',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'layout'     => 'block',
            'sub_fields' => [
               [
                  'key'               => 'field_688c34496cfe1',
                  'label'             => 'Guia',
                  'name'              => 'guide',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'page',
                  ],
                  'post_status' => [
                     0 => 'publish',
                  ],
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 0,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 0,
                  'ui'                   => 1,
                  'bidirectional_target' => [
                  ],
               ],
               [
                  'key'               => 'field_688c365d87ed0',
                  'label'             => 'Dicas',
                  'name'              => 'hints',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'page',
                  ],
                  'post_status' => [
                     0 => 'publish',
                  ],
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 0,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 0,
                  'ui'                   => 1,
                  'bidirectional_target' => [
                  ],
               ],
               [
                  'key'               => 'field_688c359287ecf',
                  'label'             => 'Painel',
                  'name'              => 'dashboard',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'page',
                  ],
                  'post_status' => [
                     0 => 'publish',
                  ],
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 0,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 0,
                  'ui'                   => 1,
                  'bidirectional_target' => [
                  ],
               ],
               [
                  'key'               => 'field_688c36a257944',
                  'label'             => 'Editar',
                  'name'              => 'edit',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type' => [
                     0 => 'page',
                  ],
                  'post_status' => [
                     0 => 'publish',
                  ],
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 0,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 0,
                  'ui'                   => 1,
                  'bidirectional_target' => [
                  ],
               ],
               [
                  'key'               => 'field_688c39ffbf4ab',
                  'label'             => 'Perfil',
                  'name'              => 'profile',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type'   => '',
                  'post_status' => [
                     0 => 'publish',
                  ],
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 0,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 0,
                  'ui'                   => 1,
                  'bidirectional_target' => [
                  ],
               ],
               [
                  'key'               => 'field_696aa2b1f307c',
                  'label'             => 'TTS',
                  'name'              => 'tts',
                  'aria-label'        => '',
                  'type'              => 'post_object',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'post_type'   => '',
                  'post_status' => [
                     0 => 'publish',
                  ],
                  'taxonomy'             => '',
                  'return_format'        => 'id',
                  'multiple'             => 0,
                  'allow_null'           => 0,
                  'allow_in_bindings'    => 0,
                  'bidirectional'        => 0,
                  'ui'                   => 1,
                  'bidirectional_target' => [
                  ],
               ],
            ],
         ],
         [
            'key'               => 'field_68a02ab223291',
            'label'             => 'Imagem para e-mail',
            'name'              => 'email-logo',
            'aria-label'        => '',
            'type'              => 'image',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'return_format'     => 'url',
            'library'           => 'all',
            'min_width'         => '',
            'min_height'        => '',
            'min_size'          => '',
            'max_width'         => '',
            'max_height'        => '',
            'max_size'          => '',
            'mime_types'        => '',
            'allow_in_bindings' => 0,
            'preview_size'      => 'medium',
         ],
      ],
      'location' => [
         [
            [
               'param'    => 'options_page',
               'operator' => '==',
               'value'    => 'camp-global',
            ],
         ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
      'display_title'         => '',
   ]);

   acf_add_local_field_group([
      'key'    => 'group_68844461152d8',
      'title'  => 'Para Guildas',
      'fields' => [
         [
            'key'               => 'field_68844463832eb',
            'label'             => 'Cor',
            'name'              => 'color',
            'aria-label'        => '',
            'type'              => 'color_picker',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'         => '#000000',
            'enable_opacity'        => 0,
            'return_format'         => 'string',
            'allow_in_bindings'     => 0,
            'custom_palette_source' => '',
            'palette_colors'        => '',
            'show_color_wheel'      => true,
         ],
         [
            'key'               => 'field_688456357681a',
            'label'             => 'Curador',
            'name'              => 'curator',
            'aria-label'        => '',
            'type'              => 'user',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'role' => [
               0 => 'editor',
               1 => 'administrator',
            ],
            'return_format'        => 'id',
            'multiple'             => 0,
            'allow_null'           => 0,
            'allow_in_bindings'    => 0,
            'bidirectional'        => 0,
            'bidirectional_target' => [
            ],
         ],
         [
            'key'               => 'field_68881a613c043',
            'label'             => 'Selo',
            'name'              => 'seal',
            'aria-label'        => '',
            'type'              => 'image',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'return_format'     => 'id',
            'library'           => 'all',
            'min_width'         => '',
            'min_height'        => '',
            'min_size'          => '',
            'max_width'         => '',
            'max_height'        => '',
            'max_size'          => '',
            'mime_types'        => '',
            'allow_in_bindings' => 0,
            'preview_size'      => 'medium',
         ],
         [
            'key'               => 'field_68883e319140c',
            'label'             => 'Ícone',
            'name'              => 'icon',
            'aria-label'        => '',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'maxlength'         => 60,
            'allow_in_bindings' => 0,
            'placeholder'       => '',
            'prepend'           => '',
            'append'            => '',
         ],
         [
            'key'               => 'field_689fe249b8b21',
            'label'             => 'Gêneros',
            'name'              => 'genres',
            'aria-label'        => '',
            'type'              => 'textarea',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'maxlength'         => '',
            'allow_in_bindings' => 0,
            'rows'              => 3,
            'placeholder'       => '',
            'new_lines'         => '',
         ],
         [
            'key'               => 'field_68efa7f90e966',
            'label'             => 'Ícone Caracter',
            'name'              => 'char',
            'aria-label'        => '',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'maxlength'         => 10,
            'allow_in_bindings' => 0,
            'placeholder'       => '',
            'prepend'           => '',
            'append'            => '',
         ],
         [
            'key'               => 'field_68f0237971ca5',
            'label'             => 'Tamanho',
            'name'              => 'size',
            'aria-label'        => '',
            'type'              => 'number',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'min'               => '',
            'max'               => '',
            'allow_in_bindings' => 0,
            'placeholder'       => '',
            'step'              => '',
            'prepend'           => '',
            'append'            => '',
         ],
         [
            'key'               => 'field_69710e538e883',
            'label'             => 'Vinheta - Intro',
            'name'              => 'intro',
            'aria-label'        => '',
            'type'              => 'file',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'return_format'     => 'url',
            'library'           => 'all',
            'min_size'          => '',
            'max_size'          => '',
            'mime_types'        => 'ogg',
            'allow_in_bindings' => 0,
         ],
         [
            'key'               => 'field_69710e9d8e884',
            'label'             => 'Vinheta - Outro',
            'name'              => 'outro',
            'aria-label'        => '',
            'type'              => 'file',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'return_format'     => 'url',
            'library'           => 'all',
            'min_size'          => '',
            'max_size'          => '',
            'mime_types'        => 'ogg',
            'allow_in_bindings' => 0,
         ],
      ],
      'location' => [
         [
            [
               'param'    => 'taxonomy',
               'operator' => '==',
               'value'    => 'club',
            ],
         ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
      'display_title'         => '',
   ]);

   acf_add_local_field_group([
      'key'    => 'group_68dce3306f9b2',
      'title'  => 'Para Séries',
      'fields' => [
         [
            'key'               => 'field_68dce330184de',
            'label'             => 'Links',
            'name'              => 'links',
            'aria-label'        => '',
            'type'              => 'repeater',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'layout'        => 'table',
            'pagination'    => 0,
            'min'           => 0,
            'max'           => 0,
            'collapsed'     => '',
            'button_label'  => 'Adicionar linha',
            'rows_per_page' => 20,
            'sub_fields'    => [
               [
                  'key'               => 'field_68dce342184df',
                  'label'             => 'Ícone',
                  'name'              => 'icon',
                  'aria-label'        => '',
                  'type'              => 'text',
                  'instructions'      => '',
                  'required'          => 0,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'default_value'     => 'ri-external-link-line',
                  'maxlength'         => '',
                  'allow_in_bindings' => 0,
                  'placeholder'       => '',
                  'prepend'           => '',
                  'append'            => '',
                  'parent_repeater'   => 'field_68dce330184de',
               ],
               [
                  'key'               => 'field_68dce455690ec',
                  'label'             => 'Texto',
                  'name'              => 'label',
                  'aria-label'        => '',
                  'type'              => 'text',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'default_value'     => '',
                  'maxlength'         => '',
                  'allow_in_bindings' => 0,
                  'placeholder'       => '',
                  'prepend'           => '',
                  'append'            => '',
                  'parent_repeater'   => 'field_68dce330184de',
               ],
               [
                  'key'               => 'field_68dce370184e0',
                  'label'             => 'Link',
                  'name'              => 'url',
                  'aria-label'        => '',
                  'type'              => 'url',
                  'instructions'      => '',
                  'required'          => 1,
                  'conditional_logic' => 0,
                  'wrapper'           => [
                     'width' => '',
                     'class' => '',
                     'id'    => '',
                  ],
                  'default_value'     => '',
                  'allow_in_bindings' => 0,
                  'placeholder'       => '',
                  'parent_repeater'   => 'field_68dce330184de',
               ],
            ],
         ],
         [
            'key'               => 'field_68e10032d624a',
            'label'             => 'Donos',
            'name'              => 'owners',
            'aria-label'        => '',
            'type'              => 'user',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'role'                 => '',
            'return_format'        => 'id',
            'multiple'             => 1,
            'allow_null'           => 0,
            'allow_in_bindings'    => 0,
            'bidirectional'        => 0,
            'bidirectional_target' => [
            ],
         ],
      ],
      'location' => [
         [
            [
               'param'    => 'taxonomy',
               'operator' => '==',
               'value'    => 'series',
            ],
         ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
      'display_title'         => '',
   ]);

   acf_add_local_field_group([
      'key'    => 'group_687edcd571aec',
      'title'  => 'Para Textos',
      'fields' => [
         [
            'key'               => 'field_687edcd59c9da',
            'label'             => 'Desafio',
            'name'              => 'challenge',
            'aria-label'        => '',
            'type'              => 'post_object',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'post_type' => [
               0 => 'challenge',
            ],
            'post_status' => [
               0 => 'publish',
            ],
            'taxonomy'             => '',
            'return_format'        => 'id',
            'multiple'             => 0,
            'allow_null'           => 1,
            'allow_in_bindings'    => 0,
            'bidirectional'        => 1,
            'bidirectional_target' => [
               0 => 'field_688663c87a9e8',
            ],
            'ui' => 1,
         ],
         [
            'key'               => 'field_6966c0744379c',
            'label'             => 'Áudio',
            'name'              => 'audio',
            'aria-label'        => '',
            'type'              => 'file',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'return_format'     => 'url',
            'library'           => 'all',
            'min_size'          => '',
            'max_size'          => '',
            'mime_types'        => 'ogg,mp3',
            'allow_in_bindings' => 0,
         ],
         [
            'key'               => 'field_68bc45aecfcd4',
            'label'             => 'Cor do texto',
            'name'              => 'color',
            'aria-label'        => '',
            'type'              => 'true_false',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'message'           => '',
            'default_value'     => 0,
            'allow_in_bindings' => 0,
            'ui_on_text'        => 'Preto',
            'ui_off_text'       => 'Branco',
            'ui'                => 1,
         ],
         [
            'key'               => 'field_68bc45cfcfcd5',
            'label'             => 'Autor da imagem',
            'name'              => 'image_author',
            'aria-label'        => '',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'maxlength'         => '',
            'allow_in_bindings' => 0,
            'placeholder'       => '',
            'prepend'           => '',
            'append'            => '',
         ],
         [
            'key'               => 'field_688078c32fdab',
            'label'             => 'Miniatura',
            'name'              => 'image_mini',
            'aria-label'        => '',
            'type'              => 'url',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'allow_in_bindings' => 0,
            'placeholder'       => '',
         ],
         [
            'key'               => 'field_68bc45eacfcd6',
            'label'             => 'URL do Autor',
            'name'              => 'image_author_url',
            'aria-label'        => '',
            'type'              => 'url',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'allow_in_bindings' => 0,
            'placeholder'       => '',
         ],
         [
            'key'               => 'field_68bc45fbcfcd7',
            'label'             => 'Imagem completa',
            'name'              => 'image_full',
            'aria-label'        => '',
            'type'              => 'url',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => '',
            'allow_in_bindings' => 0,
            'placeholder'       => '',
         ],
      ],
      'location' => [
         [
            [
               'param'    => 'post_type',
               'operator' => '==',
               'value'    => 'text',
            ],
         ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
      'display_title'         => '',
   ]);

   acf_add_local_field_group([
      'key'    => 'group_6884e3da2caae',
      'title'  => 'Para Usuários',
      'fields' => [
         [
            'key'               => 'field_6884e3dbfef28',
            'label'             => 'Nível',
            'name'              => 'xp',
            'aria-label'        => '',
            'type'              => 'number',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => [
               'width' => '',
               'class' => '',
               'id'    => '',
            ],
            'default_value'     => 0,
            'min'               => 0,
            'max'               => '',
            'allow_in_bindings' => 0,
            'placeholder'       => '',
            'step'              => 1,
            'prepend'           => '',
            'append'            => '',
         ],
      ],
      'location' => [
         [
            [
               'param'    => 'user_form',
               'operator' => '==',
               'value'    => 'edit',
            ],
         ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
      'display_title'         => '',
   ]);
});

add_action('acf/init', function() {
   acf_add_options_page([
      'page_title'  => 'Opções do tema',
      'menu_slug'   => 'camp-global',
      'parent_slug' => 'index.php',
      'position'    => '',
      'redirect'    => false,
   ]);
});
